on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'COPYING'
      - 'website/**'
      - '.github/*.md'
      - '.github/FUNDING.yml'

name: Build Code
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
    - name: Checkout code 👋
      uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
    - name: Install Go 🗳
      uses: ./.github/workflows/composite/bootstrap-go
    - name: Run GoReleaser 🚀
      uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1
      with:
        distribution: goreleaser
        version: latest
        args: build --rm-dist --snapshot --skip-post-hooks --skip-before
        workdir: src
    - name: Archive production artifacts
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
      with:
        name: builds
        retention-days: 1
        path: |
          src/dist
