name: Validate Commits

on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@d6f6593a4762bd5aa8ffb0f60127f779aca3759d
        with:
          configFile: './.commitlintrc.yml'
