name: Social
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node ⬇️
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7
        with:
          node-version: 18
      - name: Checkout code 👋
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Skyt 🌤️
        working-directory: scripts/bluesky
        env:
          BLUESKY_IDENTIFIER: ${{ secrets.BLUESKY_IDENTIFIER }}
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
          OWNER: JanDeDobbeleer
          REPO: oh-my-posh
        run: |
          npm install
          node main.js
